### ISSUE TITLE
Correcting the relationship of RouteNode, TrainStation, BusStop

### ISSUE THREAD

**Issue by Jefferson111** [AY1920S1-CS2113T-W13-3/main#117]
RouteNode is a location and should be under locations. RouteNode is either a TrainStation or a BusStop. Whereas BusStop and TrainStation is a RouteNode. 

Need establish these relationships in the code.

**Comment by Inno97** [comment]
Noted, the following changes will be made in the PR:
 - Shift RouteNode class to model.locations package
 - Make RouteNode abstract class, for BusStop and Trainstation to extend
	 - RouteNode extends Venue
	 - BusStop and TrainStation extends RouteNode

**Comment by Inno97** [comment]
Feature implementing in PR route_management.

**Comment by Inno97** [comment]
Closed in PR route_manager.
