### ISSUE TITLE
Perform cleanup of classes

### ISSUE THREAD

**Issue by Inno97** [AY1920S1-CS2113T-W13-3/main#139]
We will need to cleanup our code! 
The following must be done for each class:
 - Update exceptions
 - Add proper javadoc comments

Below is the list of all classes that have not been cleaned up:

	Commons
		Messages.java
		 
	logic
		commands
			AddCommand.java
			AddSampleItineraryCommand.java
			Command.java
			DeleteCommand.java
			DoneItineraryCommand.java
			EditCommand.java
			EditorCommand.java
			ExitCommand.java
			FindCommand.java
			HelpCommand.java
			ListCommand.java
			ListItineraryCommand.java
			LocationSearchCommand.java
			MarkDoneCommand.java
			NewItineraryCommand.java
			ProfileAddCommand.java
			ProfileSetPreferenceCommand.java
			ProfileShowCommand.java
			PromptCommand.java
			QuickEditCommand.java
			RecommendationsCommand.java
			ShowItineraryCommand.java
			ViewScheduleCommand.java
		
		editor
			Editor.java
			EditorManager.java
		
		selectors
			EventFieldSelector.java
			LocationHelper.java
			LocationSelector.java
			Selector.java
			
		Logic.java
		LogicManager.java
		PathFinder.java
	
	model
		profile
			Person.java
			Preference.java
			ProfileCard.java
			
		Task.java
		TaskWithDates.java
		
	storage
		SampleStorage.java
		Storage.java
	
	ui
		
		UiPart.java
	
	Launcher.java
	Main.java

**Comment by Inno97** [comment]
Cleared the following:
	commons
		commands
			RouteAddCommand.java
			RouteDeleteCommand.java
			RouteEditCommand.java
			RouteListAllCommand.java
			RouteListCommand.java
			RouteNodeAddCommand.java
			RouteNodeDeleteCommand.java
			RouteNodeEditCommand.java
			RouteNodeListCommand.java
		Messages.java
		
	logic
		api
			requests
				LocationSearchUrlRequest
				StaticMapRequest
				UrlRequest

	model
		lists
			RouteList.java
	
		locations
			BusStop.java
			RouteNode.java
			TrainStation.java
			Venue.java
		
		transports
			BusService.java
			Route.java
			
	storage
		Storage.java

**Comment by Inno97** [comment]
Cleared the following:

enumerations
		Constraint.java
		Direction.java
		TimePatternType.java
	 
	exceptions
		ApiException.java
		ChronologyAfterPresentException.java
		ChronologyBeforePresentException.java
		ChronologyInconsistentException.java
		DukeException.java
		DuplicateRouteException.java
		DuplicateRouteNodeException.java
		DuplicateTaskException.java
		EmptyVenueException.java
		EventNotSelectedException.java
		FileLoadFailException.java
		FileNotSavedException.java
		HelpFailException.java
		InputNotDoubleException.java
		NoRecentItineraryException.java
		NoSuchBusServiceException.java
		NoSuchBusStopException.java
		NoSuchCategoryException.java
		NoSuchItineraryException.java
		NoSuchRouteException.java
		NullResultException.java
		OutOfBoundsException.java
		ParseException.java
		QueryFailedException.java
		RecommendationFailException.java
		RouteGenerateFailException.java
		UnknownConstraintException.java
		UnknownFieldException.java
	 
	Messages.java
	 
logic
	api
		requests
			LocationSearchRequest.java
			LocationSearchUrlRequest.java
			StaticMapUrlRequest.java
			UrlRequest.java

		ApiConstraintParser.java
		ApiParser.java

**Comment by Inno97** [comment]
Cleared the following:

lists
			EventList.java
			Listable.java
			RouteList.java
			VenueList.java

		locations
			BusStop.java
			CustomNode.java
			RouteNode.java
			TrainStation.java
			Venue.java

		planning
			Agenda.java
			Itinerary.java
			Recommendation.java
			Todo.java
			
		
		
		transports
			BusService.java
			Route.java
			TransportationMap.java
			
		Event.java
		Model.java
		ModelManager.java

**Comment by Jefferson111** [comment]
Clear:
```
parsers package
```
