### ISSUE TITLE
Cleanup the API package

### ISSUE THREAD

**Issue by Jefferson111** [AY1920S1-CS2113T-W13-3/main#95]
Replace constant strings with capital letters,  remove unused code, refactoring, improve code quality

**Comment by Jefferson111** [comment]
Also the blank space in location bug ```Changi Airport``` , currently need no space location like ```Esplanade```

**Comment by Inno97** [comment]
> Also the blank space in location bug `Changi Airport` , currently need no space location like `Esplanade`

Fixed.

**Comment by Inno97** [comment]
Fixed in v1.2
